name: Build new custom caddy image
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  KIWIIRC_VERSION: 1.6.1

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,arm"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.KIWIIRC_VERSION }}
